# Generated by Django 4.1 on 2022-09-19 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MywatchlistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('watched', models.BooleanField()),
                ('title', models.CharField(max_length=255)),
                ('rating', models.IntegerField(blank=True, choices=[(5, 'very good'), (4, 'good'), (3, 'mediocre'), (2, 'bad'), (1, 'very bad')], null=True)),
                ('release_date', models.DateField()),
                ('review', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
