# Generated by Django 4.1 on 2022-09-19 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mywatchlist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mywatchlistitem',
            name='rating',
            field=models.IntegerField(choices=[('very good', 5), ('good', 4), ('mediocre', 3), ('bad', 2), ('very bad', 1)], null=True),
        ),
        migrations.AddField(
            model_name='mywatchlistitem',
            name='watched',
            field=models.CharField(choices=[('watched', 'Sudah ditonton'), ('not_watched', 'Belum ditonton')], default='not_watched', max_length=50),
        ),
    ]
