# Generated by Django 4.1 on 2022-09-19 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mywatchlist', '0002_mywatchlistitem_rating_mywatchlistitem_watched'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mywatchlistitem',
            name='rating',
            field=models.CharField(choices=[('very good', 5), ('good', 4), ('mediocre', 3), ('bad', 2), ('very bad', 1)], max_length=50, null=True),
        ),
    ]
