# Generated by Django 4.1 on 2022-09-19 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mywatchlist', '0003_alter_mywatchlistitem_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mywatchlistitem',
            name='rating',
            field=models.CharField(choices=[(5, 'very good'), (4, 'good'), (3, 'mediocre'), (2, 'bad'), (1, 'very bad')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='mywatchlistitem',
            name='watched',
            field=models.CharField(choices=[('Sudah ditonton', 'watched'), ('Belum ditonton', 'not_watched')], default='not_watched', max_length=50),
        ),
    ]
