# Generated by Django 4.1 on 2022-09-19 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mywatchlist', '0004_alter_mywatchlistitem_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mywatchlistitem',
            name='rating',
            field=models.IntegerField(choices=[(5, 'very good'), (4, 'good'), (3, 'mediocre'), (2, 'bad'), (1, 'very bad')], null=True),
        ),
    ]
