# Generated by Django 4.1 on 2022-09-19 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mywatchlist', '0006_alter_mywatchlistitem_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mywatchlistitem',
            name='review',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mywatchlistitem',
            name='watched',
            field=models.BooleanField(default=False),
        ),
    ]
