# Generated by Django 4.1 on 2022-09-19 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mywatchlist', '0007_alter_mywatchlistitem_review_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mywatchlistitem',
            name='watched',
            field=models.BooleanField(),
        ),
    ]
